lib/storex_web/router.ex
defmodule StorexWeb.Router do
  use StorexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StorexWeb do
    pipe_through :browser # Use the default browser stack

    get "/", BookController, :index
    get "/books", BookController, :index
    get "/books/:id", BookController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", StorexWeb do
  #   pipe_through :api
  # end
end

lib/storex/application.ex
defmodule Storex.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Storex.Repo, []),
      # Start the endpoint when the application starts
      supervisor(StorexWeb.Endpoint, []),
      # Start your own worker by calling: Storex.Worker.start_link(arg1, arg2, arg3)
      # worker(Storex.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Storex.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    StorexWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/storex/repo.ex
defmodule Storex.Repo do
  use Ecto.Repo, otp_app: :storex

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/storex/store/book.ex
defmodule Storex.Store.Book do
  use Ecto.Schema
  import Ecto.Changeset


  schema "store_books" do
    field :description, :string
    field :image_url, :string
    field :price, :decimal
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(book, attrs) do
    book
    |> cast(attrs, [:title, :description, :price, :image_url])
    |> validate_required([:title, :description, :price, :image_url])
    |> validate_max_price(:price, 99.99)
  end

  def validate_max_price(changeset, field, amount) do
    price = get_change(changeset, field)
    if Decimal.cmp(price, Decimal.new(amount)) == :gt do
      add_error(changeset, field, "Price is too high")
    else
      changeset
    end
  end
end

lib/storex/store/store.ex
defmodule Storex.Store do
  alias Storex.Repo
  alias Storex.Store.Book

  def create_book(attrs) do
    %Book{}
    # Book.changeset holds all the validation
    |> Book.changeset(attrs)
    |> Repo.insert!()
  end

  def list_books() do
    Repo.all(Book)
  end

  def get_book(id) do
    Repo.get(Book, id)
  end
end

lib/storex_web/controllers/book_controller.ex
defmodule StorexWeb.BookController do
  use StorexWeb, :controller
  alias Storex.Store

  def index(conn, _params) do
    render conn, "index.html", books: Store.list_books()
  end

  def show(conn, %{"id" => book_id}) do
    book = Store.get_book(book_id)
    render conn, "show.html", book: book
  end
end

lib/storex_web/controllers/page_controller.ex
defmodule StorexWeb.PageController do
  use StorexWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/storex_web/views/book_view.ex
defmodule StorexWeb.BookView do
  use StorexWeb, :view
end

lib/storex_web/views/error_view.ex
defmodule StorexWeb.ErrorView do
  use StorexWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/storex_web/views/layout_view.ex
defmodule StorexWeb.LayoutView do
  use StorexWeb, :view
end

lib/storex_web/views/page_view.ex
defmodule StorexWeb.PageView do
  use StorexWeb, :view
end

lib/storex_web/templates/book/index.html.eex
<section class="book-list">
  <ul class="grid">
    <%= for book <- @books do %>
    <li class="grid-item">
      <div class="book book-small">
        <%= link to: book_path(@conn, :show, book.id) do %>
          <img class="book__image" src="<%= book.image_url %>">
          <h2 class="book__title"><%= book.title %></h2>
        <% end %>
        <span class="book__price"><%= book.price %></span>
      </div>
    </li>
    <% end %>
  </ul>
</section>

lib/storex_web/templates/book/show.html.eex
<h1><%= @book.title %></h1>

<div class="book book-hero">
  <img class="book__image" src="<%= @book.image_url %>">

  <p class="book__description">
    <%= @book.description %>
  </p>
</div>

<div class="value-tag">
  <h2 class="value-tag__title">price</h2>
  <span class="value-tag__content"><%= @book.price %></span>
</div>

lib/storex_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf­8">
  <meta http­equiv="X­UA­Compatible" content="IE=edge">
  <meta name="viewport" content="width=device­width, initial­scale=1">
  <title>Welcome to Storex</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>"> </head>

<body>
  <nav class="main-nav">
    <a class="main-nav__logo" href="/"></a>
  </nav>
  <main class="content">
    <%= if message=get_flash(@conn, :info) do %>
      <p class="alert alert-info" role="alert">
        <%= message %>
      </p>
    <% end %>
    <%= if message=get_flash(@conn, :error) do %>
      <p class="alert alert-danger" role="alert">
        <%= message %>
      </p>
    <% end %>
    <%= render @view_module, @view_template, assigns %>
  </main>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script> </body>
</html>

lib/storex_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>